In [1]:
# NumPy 예제
import numpy as np

In [2]:
# 1차원 배열 생성
arr1 = np.zeros(4)

print(arr1)

arr2 = np.empty(0)

print(arr2)

list = [1, 2, 3, 4]
arr3 = np.array(list)
print(arr3)

[0. 0. 0. 0.]
[]
[1 2 3 4]


In [3]:
arr4 = np.zeros((2,3))
print(arr4)
print(f"차원수 : {arr4.ndim}")
print(f"모양 : {arr4.shape}")
print(f"전체개수 : {arr4.size}")
print(f"타입 : {arr4.dtype}")

[[0. 0. 0.]
 [0. 0. 0.]]
차원수 : 2
모양 : (2, 3)
전체개수 : 6
타입 : float64


In [4]:
arr5 = np.array([1,2,3,4,5,6])
print(arr5)
arr6 = arr5.reshape(2,3)
print(arr6)
arr7 = arr5.reshape(3, -1)
print(arr7)
arr8 = arr5.reshape(-1, 1)
print(arr8)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
# 인덱싱과 슬라이싱
arr9 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("기본 배열 : ")
print(arr9)
# 0행 조회
print("0행 조회 : ")
print(arr9[0])
# 0행 1열 조회
print("0행 1열 조회 : ")
print(arr9[0,1])
# 1열 조회
print("1열 조회 : ")
print(arr9[:,1])
# 값이 4보다 큰 값 조회
print("4보다 큰 값 조회 : ")
print(arr9[arr9 > 4])
# 행 : 0이상 2미만, 열: 전체
print("행 : 0이상 2미만, 열: 전체 조회 : ")
print(arr9[0:2, :])
# 헹 : 1이상 3미만, 열: 1이상 2미만(1열)
print("행 : 1이상 3미만, 열: 1이상 2미만(1열) : ")
print(arr9[1:3, 1:2])
# -는 뒤에서부터
# 행 : 전체, 열 : 마지막 1열
print("행 : 전체, 열 : 마지막 1열 : ")
print(arr9[ : , -1])

기본 배열 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
0행 조회 : 
[1 2 3]
0행 1열 조회 : 
2
1열 조회 : 
[2 5 8]
4보다 큰 값 조회 : 
[5 6 7 8 9]
행 : 0이상 2미만, 열: 전체 조회 : 
[[1 2 3]
 [4 5 6]]
행 : 1이상 3미만, 열: 1이상 2미만(1열) : 
[[5]
 [8]]
행 : 전체, 열 : 마지막 1열 : 
[3 6 9]


In [6]:
# 집계 함수
scores = np.array([
	[100, 90, 80], # 홍길동의 국어, 영어, 수학
 	[90, 40, 100], # 고길동의 국어, 영어, 수학
 	[10, 10, 100], # 홍길동의 국어, 영어, 수학
])

print(f"전체 평균 : {scores.mean()}")
print(f"홍길동의 평균 : {scores[0].mean()}")
print(f"국어 평균 : {scores[:, 0].mean()}")
print(f"영어 최고점 : {scores[:, 1].max()}")
print(f"수학 최저점 위치 : {scores[:, 2].argmin()}")
print(f"각 과목의 총점 : {scores.sum(axis=0)}")
print(f"각 학생의 총점 : {scores.sum(axis=1)}")

전체 평균 : 68.88888888888889
홍길동의 평균 : 90.0
국어 평균 : 66.66666666666667
영어 최고점 : 90
수학 최저점 위치 : 0
각 과목의 총점 : [200 140 280]
각 학생의 총점 : [270 230 120]


In [7]:
# 난수 생성
rand_array = np.random.rand(3, 3)
print(rand_array)

# 정수 난수 생성
rand_array2 = np.random.randint(1,10,12)
print(rand_array2)
rand_array2 = rand_array2.reshape(3,-1)
print(rand_array2)

# 정수 난수 생성
rand_array3 = np.random.randint(1,10,12)
print(rand_array3)
np.random.shuffle(rand_array3)
rand_array3 = rand_array3.reshape(3,-1)
print(rand_array3)

[[0.96464327 0.56099654 0.70184577]
 [0.5733196  0.36459941 0.5045968 ]
 [0.54372069 0.72523243 0.00675541]]
[3 6 7 8 7 5 4 1 7 7 1 7]
[[3 6 7 8]
 [7 5 4 1]
 [7 7 1 7]]
[2 8 5 2 7 5 7 1 9 1 1 4]
[[7 5 8 2]
 [7 1 9 5]
 [2 1 1 4]]
